[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"

[tool.ruff]
line-length = 120

[tool.pylint]
max-line-length = 120

[tool.flake8]
max-line-length = 120
ignore = "skip"
per-file-ignores = ['__init__.py:F401']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
